export * from './filter';
export * from './find';
export * from './findIndex';
export * from './map';
export * from './reduce';
export * from './curry';
export * from './reduceRight';
export * from './last';
export * from './head';